
# примеры API-запросов

# @baseUrl = http://localhost:8088
@baseUrl = http://localhost:5500


# Получить Список переводов
GET {{baseUrl}}/transfer
Content-Type: application/json

###

# Выполнить Перевод с карты на карту
POST {{baseUrl}}/transfer
Content-Type: application/json

{
  "cardFromNumber": "1234567890123456",
  "cardFromValidTill": "02/34",
  "cardFromCVV": "231",
  "cardToNumber": "2345678901234561",
  "amount": {
    "value": 2000,
    "currency": "RUR"
  }
}

###

# Выполнить Перевод с ERR: amount.value
POST {{baseUrl}}/transfer
Content-Type: application/json

{
  "cardFromNumber": "1234567890123456",
  "cardFromValidTill": "02/34",
  "cardFromCVV": "231",
  "cardToNumber": "2345678901234561",
  "amount": {
    "value": -1000,
    "currency": "RUR"
  }
}

###

# Выполнить Перевод с ERR: cardFromCVV
POST {{baseUrl}}/transfer
Content-Type: application/json

{
  "cardFromNumber": "1234567890123456",
  "cardFromValidTill": "02/34",
  "cardFromCVV": "23100000",
  "cardToNumber": "2345678901234561",
  "amount": {
    "value": 1000,
    "currency": "RUR"
  }
}

###

# Выполнить Перевод с ERR: bad card number (cardFromNumber)
POST {{baseUrl}}/transfer
Content-Type: application/json

{
  "cardFromNumber": "1234567890120",
  "cardFromValidTill": "02/34",
  "cardFromCVV": "999",
  "cardToNumber": "2345678901234561",
  "amount": {
    "value": 999,
    "currency": "RUR"
  }
}

###

# Выполнить Перевод с ERR: bad card number (cardToNumber)
POST {{baseUrl}}/transfer
Content-Type: application/json

{
  "cardFromNumber": "1234567890123456",
  "cardFromValidTill": "02/34",
  "cardFromCVV": "999",
  "cardToNumber": "2345678901230",
  "amount": {
    "value": 999,
    "currency": "RUR"
  }
}

###

# Выполнить Перевод с ERR: is overdue date
POST {{baseUrl}}/transfer
Content-Type: application/json

{
  "cardFromNumber": "1234567890123456",
  "cardFromValidTill": "01/24",
  "cardFromCVV": "231",
  "cardToNumber": "2345678901234561",
  "amount": {
    "value": 100000000,
    "currency": "RUR"
  }
}

###

# Выполнить Перевод с ERR: bad date
POST {{baseUrl}}/transfer
Content-Type: application/json

{
  "cardFromNumber": "1234567890123456",
  "cardFromValidTill": "01/yy",
  "cardFromCVV": "231",
  "cardToNumber": "2345678901234561",
  "amount": {
    "value": 100000000,
    "currency": "RUR"
  }
}

###

# Выполнить Перевод с ERR: is overdue date
POST {{baseUrl}}/transfer
Content-Type: application/json

{
  "cardFromNumber": "1234567890123456",
  "cardFromValidTill": "1234",
  "cardFromCVV": "231",
  "cardToNumber": "2345678901234561",
  "amount": {
    "value": 100000000,
    "currency": "RUR"
  }
}

###

